In [139]:
import thunder
from collections import defaultdict
import numpy

In [299]:
data = sc.textFile("test_matrix.txt")
data2 = data.map(lambda l: l.split(','))
data3 = data2.map(lambda l: [int(s) for s in l])
data4 = data3.map(lambda l: (l[0], l[1:]))
data4.take(2)

[(1, [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]), (2, [0, 0, 0, 0, 0, 0, 0, 0, 0, 1])]

In [300]:
a = thunder.RowMatrix(data4)
a.take(10)

[(1, [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]),
 (2, [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 (3, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 (4, [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]),
 (5, [1, 0, 1, 0, 1, 0, 0, 0, 0, 0]),
 (6, [0, 0, 0, 0, 0, 1, 0, 1, 0, 1]),
 (7, [0, 0, 1, 0, 1, 0, 1, 0, 0, 0]),
 (8, [0, 0, 0, 1, 0, 1, 0, 1, 0, 0]),
 (9, [1, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 (10, [0, 0, 0, 1, 0, 0, 0, 0, 0, 1])]

In [301]:
b = thunder.SVD(3)

In [302]:
c = b.calc(a)

In [317]:
c.u.collect()

[(1, array([  6.77487186e-01,   1.59046550e-16,   2.33879773e-16])),
 (2, array([  3.79711331e-17,  -1.57040477e-01,   6.00771718e-03])),
 (3, array([  1.57040477e-01,   4.82709538e-17,  -5.77319011e-01])),
 (4, array([  2.17800843e-16,  -6.77487186e-01,   1.40512602e-16])),
 (5, array([  4.71121432e-01,   1.09088928e-16,  -9.43689571e-16])),
 (6, array([  1.13948721e-16,  -4.71121432e-01,  -1.53523028e-16])),
 (7, array([  4.54061942e-01,   9.99152438e-17,   5.77319011e-01])),
 (8, array([  1.10323453e-16,  -4.54061942e-01,  -6.00771718e-03])),
 (9, array([  2.97021465e-01,   8.73682231e-17,  -5.77319011e-01])),
 (10, array([  7.23169981e-17,  -2.97021465e-01,   6.00771718e-03]))]

In [304]:
c.v.T

array([[  5.01681323e-01,   1.54206332e-16,  -8.16452375e-01],
       [  2.22044605e-16,  -2.12072697e-01,   4.44089210e-16],
       [  5.01681323e-01,   3.19189120e-16,   4.08226188e-01],
       [  1.09721260e-16,  -4.47183097e-01,  -2.77555756e-17],
       [  5.01681323e-01,  -1.24900090e-16,   4.08226188e-01],
       [  1.21358957e-16,  -5.01681323e-01,  -4.24809756e-03],
       [  4.47183097e-01,   1.24900090e-16,   1.27675648e-15],
       [  1.21358957e-16,  -5.01681323e-01,  -4.24809756e-03],
       [  2.12072697e-01,   3.46944695e-17,   3.88578059e-16],
       [  1.21302537e-16,  -5.01681323e-01,   8.49619512e-03]])

In [305]:
c.s

array([ 3.19459882,  3.19459882,  1.41421356])

In [318]:
array = c.v.T*c.u[1]

In [319]:
array2 = array*c.s

In [320]:
array2

array([[  1.08578877e+00,   7.83506829e-32,  -2.70046479e-16],
       [  4.80571086e-16,  -1.07752000e-16,   1.46885147e-31],
       [  1.08578877e+00,   1.62176775e-31,   1.35023239e-16],
       [  2.37469697e-16,  -2.27209224e-16,  -9.18032170e-33],
       [  1.08578877e+00,  -6.34604770e-32,   1.35023239e-16],
       [  2.62657162e-16,  -2.54899224e-16,  -1.40508353e-18],
       [  9.67838271e-01,   6.34604770e-32,   4.22294798e-31],
       [  2.62657162e-16,  -2.54899224e-16,  -1.40508353e-18],
       [  4.58988887e-01,   1.76279103e-32,   1.28524504e-31],
       [  2.62535052e-16,  -2.54899224e-16,   2.81016706e-18]])